networks:
  ztp:
    driver: bridge

services:
  postgres-cart-api:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data/cart:/var/lib/postgresql/data
    hostname:
      shopping-cart-postgres
    networks:
      - ztp
    container_name:
      carts-postgres

  postgres-products-api:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data/products:/var/lib/postgresql/data
    hostname:
      products-postgres
    networks:
      - ztp
    container_name:
      products-postgres

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres-data
      o: bind
