networks:
  ztp:
    driver: bridge

services:
  postgres-cart-api:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data/cart:/var/lib/postgresql/data
    hostname:
      shopping-cart-postgres
    networks:
      - ztp
    container_name:
      carts-postgres

  postgres-products-api:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data/products:/var/lib/postgresql/data
    hostname:
      products-postgres
    networks:
      - ztp
    container_name:
      products-postgres

  products-api:
    build:
      context: ./products-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    environment:
      - SERVER_PORT=8001
      - POSTGRES_HOST=postgres-products-api
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SSL_MODE=disable
      - POSTGRES_DB_NAME=postgres
    networks:
      - ztp
    depends_on:
      - postgres-products-api

  cart-api:
    build:
      context: ./cart-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
      - POSTGRES_HOST=postgres-cart-api
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SSL_MODE=disable
      - POSTGRES_DB_NAME=postgres
      - PRODUCTS_API_URL=http://products-api:8001
    networks:
      - ztp
    depends_on:
      - postgres-cart-api
      - products-api

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8002:8002"
    environment:
      - SERVER_PORT=8002
      - CARTS_API_URL=http://cart-api:8000
      - PRODUCTS_API_URL=http://products-api:8001
    networks:
      - ztp
    depends_on:
      - cart-api
      - products-api

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres-data
      o: bind
